const CHUNK_PUBLIC_PATH = "server/app/page.js";
const runtime = require("../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/9b46a_next_dist_4d4b94._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__adba9d._.js");
runtime.loadChunk("server/chunks/ssr/_47f061._.js");
runtime.loadChunk("server/chunks/ssr/src_app_globals_b80590.css");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_769957._.js");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_2ed9c8._.js");
runtime.loadChunk("server/chunks/ssr/_03722e._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/.pnpm/next@15.0.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_1 => \"[project]/node_modules/.pnpm/next@15.0.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
